=== graeme-lockley/jdbc-8-maven-plugin/src/main/resources/xsd/jdbc-8-maven-plugin-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:configuration="http://www.no9.co.za/xsd/jdbc-8-maven-plugin-configuration.xsd"
           targetNamespace="http://www.no9.co.za/xsd/jdbc-8-maven-plugin-configuration.xsd"
           elementFormDefault="qualified">
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="source" type="configuration:SourceType"/>
                <xs:element name="targets" type="configuration:TargetTypes"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SourceType">
        <xs:sequence>
            <xs:element name="jdbc" type="configuration:JdbcType"/>
            <xs:element name="tables" type="configuration:TablesType"/>
            <xs:element name="foreign-keys" type="configuration:ForeignKeysType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="JdbcType">
        <xs:sequence>
            <xs:element name="driver" type="xs:string"/>
            <xs:element name="url" type="xs:string"/>
            <xs:element name="username" type="xs:string" minOccurs="0"/>
            <xs:element name="password" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TablesType">
        <xs:sequence>
            <xs:element name="db-search" type="configuration:DBSearchType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="include" type="configuration:TablePatternType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="exclude" type="configuration:TablePatternType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DBSearchType">
        <xs:sequence>
            <xs:element name="catalog" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="schema-pattern" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="table-pattern" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TablePatternType">
        <xs:sequence>
            <xs:element name="schema" type="xs:string" minOccurs="0"/>
            <xs:element name="table" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ForeignKeysType">
        <xs:sequence>
            <xs:element name="foreign-key" type="configuration:ForeignKeyType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ForeignKeyType">
        <xs:attribute name="from-table" type="xs:string"/>
        <xs:attribute name="from-name" type="xs:string"/>
        <xs:attribute name="from-fields" type="xs:string"/>
        <xs:attribute name="to-table" type="xs:string"/>
        <xs:attribute name="to-name" type="xs:string"/>
        <xs:attribute name="to-fields" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="TargetTypes">
        <xs:sequence>
            <xs:element name="target" type="configuration:TargetType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TargetType">
        <xs:sequence>
            <xs:element name="handler" type="xs:string"/>
            <xs:element name="destination" type="xs:string"/>
            <xs:element name="properties" type="configuration:PropertiesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PropertiesType">
        <xs:sequence>
            <xs:element name="property" type="configuration:PropertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PropertyType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== graeme-lockley/jdbc-8-maven-plugin/src/test/resources/valid-jsqldsl.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns="http://www.no9.co.za/xsd/jdbc-8-maven-plugin-configuration.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.no9.co.za/xsd/jdbc-8-maven-plugin-configuration.xsd">
    <source>
        <jdbc>
            <driver>org.h2.Driver</driver>
            <url>jdbc:h2:mem:</url>
            <username>sa</username>
        </jdbc>

        <tables>
            <include>
                <schema>PUBLIC</schema>
            </include>
            <exclude>
                <schema>PUBLIC</schema>
                <table>bob</table>
            </exclude>
        </tables>
    </source>

    <targets>
        <target>
            <handler>za.co.no9.jdbcdry.model.HandlerTest</handler>
            <destination>../generated-test-sources/jsqldsl</destination>
            <properties>
                <property name="package" value="x.y.z"/>
                <property name="driver" value="za.co.no9.jdbcdry.drivers.H2"/>
            </properties>
        </target>
    </targets>
</configuration>
